name: Host Service CI

 # main branch에 있는 .js 파일이 변경되면(push) 아래와 같은 작업이 수행이 된다.
on:
  push:
    branches: [ "main" ]
    paths: ["*.js"]

jobs:
  buildImage:
    runs-on: ubuntu-latest   # container의 운영체제는 ubuntu를 기반으로 한다.
    steps:
      - name: 1. Checkout
        uses: actions/checkout@v3    # checkout = source를 가져오는 것 => 현재 파이프라인이 돌아가는 곳에서 우분투 os 아래에 소스코드를 가져온다?

      - name: 2. Login to DockerHub
        uses: docker/login-action@v2
        with: 
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    

      - name: 3. Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with: 
          push: true
          tags: chani17/hostservice:${{ github.sha }}

  updateYaml:
    runs-on: ubuntu-latest
    needs: buildImage    # updateYaml은 BuildImage가 끝나야 한다.
    steps:
      - name: 1. Checkout
        uses: actions/checkout@v3
        with:
          repository: 'chani17/hostsvc-cd'
          token: ${{ secrets.GIT_TOKEN }}
      
      - name: 2. Change Docker Tag
        run: |
          sed -i "s/image: chani17\/node-app:.*/images: chani17\/node-app:1.0/g" hostservice-deploy.yml
          git config --global user.email "cucute8878@naver.com"
          git config --global user.name "chani17"
          git commit -am "triggered by github action"
          git push origin main



    
